POST http://localhost:5000/user/suggest HTTP/1.1
Content-Type: application/json
//Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InFAcSIsImlkIjoiNjA1M2JhZWY0ODdhM2Q0NWE3OGMzNTdkIiwiaWF0IjoxNjE2MjYwNDE0LCJleHAiOjE2MTYzNDY4MTR9.umf_gj5QBxurJXneqhI9sYIsDUl8Mqw69fxOd45Gk_A

{
"wantedListOwnerId":"605a57216bfbc91f5b72d283",
"suggestion":"slimu animu desu kane",
"message":"yes please watch"

}


